parameters:
    pim_magento_connector.builder.table_name.class: Pim\Bundle\MagentoConnectorBundle\Builder\TableNameBuilder

services:
    pim_magento_connector.builder.table_name:
        class: %pim_magento_connector.builder.table_name.class%
        arguments:
            - '@service_container'
            - '@pim_catalog.doctrine.smart_manager_registry'
