show_configuration:
    -
        title: Connection
        elements:
            magentoUrl:
                type: 'url'
            wsdlUrl: ~
            soapUsername: ~
    -
        title: General
        elements:
            channel: ~
            defaultLocale:
                class: 'label label-info'
            currency:
                class: 'label label-info'
            enabled: ~
            visibility: ~
            website: ~
    -
        title: Associations mapping
        elements:
            pimGrouped: ~
            pimUpSell: ~
            pimCrossSell: ~
            pimRelated: ~
    -
        title: Behaviors
        elements:
            notInPimAnymoreAction: ~
            notCompleteAnymoreAction: ~
edit_configuration:
    -
        title: Connection
        elements:
            magentoUrl: ~
            wsdlUrl: ~
            soapUsername: ~
    -
        title: General
        elements:
            channel: ~
            defaultLocale: ~
            currency: ~
            enabled: ~
            visibility: ~
            website: ~
    -
        title: Associations mapping
        elements:
            pimGrouped: ~
            pimUpSell: ~
            pimCrossSell: ~
            pimRelated: ~
    -
        title: Behaviors
        elements:
            notInPimAnymoreAction: ~
            notCompleteAnymoreAction: ~
    -
        title: Mapping
        elements:
            storeviewMapping: ~
            categoryMapping: ~
            attributeMapping: ~
