parameters:
    pim_magento_connector.event_subscriber.cascade_delete_delta.class: Pim\Bundle\MagentoConnectorBundle\EventSubscriber\CascadeDeleteDeltaSubscriber

services:
    pim_magento_connector.event_subscriber.cascade_delete_delta:
        class: %pim_magento_connector.event_subscriber.cascade_delete_delta.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@pim_magento_connector.builder.table_name'
        tags:
            - { name: kernel.event_subscriber }
