parameters:
    pim_magento_connector.merger.mapping.class:        Pim\Bundle\MagentoConnectorBundle\Merger\MagentoMappingMerger
    pim_magento_connector.merger.addition_not_allowed: false
    pim_magento_connector.merger.addition_allowed:     true

services:
    pim_magento_connector.merger.attribute_code_mapping:
        class: %pim_magento_connector.merger.mapping.class%
        arguments:
            - ['@pim_magento_connector.mapper.magento_attribute_code', '@pim_magento_connector.mapper.orm_attribute_code']
            - 'attributeCode'
            - 'export'
            - %pim_magento_connector.merger.addition_allowed%

    pim_magento_connector.merger.attribute_id_mapping:
        class: %pim_magento_connector.merger.mapping.class%
        arguments:
            - ['@pim_magento_connector.mapper.magento_attribute_id', '@pim_magento_connector.mapper.orm_exported_attribute']
            - 'attributeId'
            - 'export'
            - %pim_magento_connector.merger.addition_not_allowed%

    pim_magento_connector.merger.storeview_mapping:
        class: %pim_magento_connector.merger.mapping.class%
        arguments:
            - ['@pim_magento_connector.mapper.magento_storeview', '@pim_magento_connector.mapper.orm_storeview']
            - 'storeview'
            - 'export'
            - %pim_magento_connector.merger.addition_allowed%

    pim_magento_connector.merger.category_mapping:
        class: %pim_magento_connector.merger.mapping.class%
        arguments:
            - ['@pim_magento_connector.mapper.magento_category', '@pim_magento_connector.mapper.orm_category']
            - 'category'
            - 'export'
            - %pim_magento_connector.merger.addition_not_allowed%
