parameters:
    pim_magento_connector.step.prune.class:                   Pim\Bundle\MagentoConnectorBundle\Step\PruneStep
    pim_magento_connector.item.magento_item_step.class:       Pim\Bundle\MagentoConnectorBundle\Item\MagentoItemStep
    pim_magento_connector.twig.configuration_extension.class: Pim\Bundle\MagentoConnectorBundle\Twig\ConfigurationExtension

services:
    pim_magento_connector.twig.configuration_extension:
        class: '%pim_magento_connector.twig.configuration_extension.class%'
        arguments:
            name: @file_locator
        tags:
            - { name: twig.extension }

    pim_magento_connector.item.magento_item_step:
        class: '%pim_magento_connector.item.magento_item_step.class%'
        abstract: true
        calls:
            - [setEventDispatcher, [@event_dispatcher]]
