Pim\Bundle\MagentoConnectorBundle\Entity\MagentoGroupMapping:
    type: entity
    table: pim_magento_group_mapping
    uniqueConstraints:
        pim_magento_group_mapping_uc:
            columns:
                - magento_url
                - pim_group_code
                - pim_family_code
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        magentoUrl:
            type: string
            length: 255
            column: magento_url
        magentoGroupId:
            type: integer
            column: magento_group_id
        pimGroupCode:
            type: string
            column: pim_group_code
        pimFamilyCode:
            type: string
            column: pim_family_code
