Pim\Bundle\MagentoConnectorBundle\Entity\MagentoAttributeMapping:
    type: entity
    table: pim_magento_attribute_mapping
    uniqueConstraints:
        pim_magento_attribute_mapping_uc:
            columns:
                - attribute_id
                - magento_url
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        magentoUrl:
            type: string
            length: 255
            column: magento_url
        magentoAttributeId:
            type: integer
            column: magento_attribute_id
    manyToOne:
        attribute:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\Attribute
            inversedBy: magentoAttributeMappings
            joinColumn:
                name: attribute_id
                referencedColumnName: id
                onDelete: 'CASCADE'
